######################################################################
# Automatically generated by qmake (3.0) ?? 9? 13 09:00:49 2016
######################################################################

TEMPLATE = app
TARGET = proxy-qt4
INCLUDEPATH += .
QT += network
QT -= gui

QMAKE_CXXFLAGS += "-std=c++11"

# Input
SOURCES += appMain.cpp \
	LocalServer.cpp \
	Utilities.cpp \
	Connections.cpp

HEADERS += LocalServer.h \
	Utilities.h \
	Connections.h
